CREATE TABLE "user" (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	username VARCHAR(255) UNIQUE NOT NULL,
	"age" INT4 NOT NULL,
	"password" VARCHAR(255) NOT NULL,
	birthdate DATE
);

CREATE TABLE address (
	id SERIAL PRIMARY KEY,
	user_id INT4 UNIQUE NOT NULL REFERENCES "user"(id),
	state VARCHAR(255) NOT NULL,
	city VARCHAR(255) NOT NULL,
	street VARCHAR(255) NOT NULL,
	"number" INT4 NOT NULL
);